# ---------------------------------------------------------
# BANCO DE DADOS (POSTGRESQL)
# ---------------------------------------------------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/glowup}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------------------------------------
# HIBERNATE / JPA
# ---------------------------------------------------------
# TODO: Retornar para 'validate' assim que a equipe entregar os scripts do Flyway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logar as queries no terminal para debug durante o desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------
# SERIALIZAÇÃO JSON
# ---------------------------------------------------------
spring.jackson.time-zone=America/Sao_Paulo